In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Read the dataset

In [0]:
import pandas as pd
df = pd.read_csv("/content/drive/My Drive/bank.csv")

# Drop the columns which are unique for all users like IDs (5 points)

In [6]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
df = df.drop(["RowNumber","CustomerId","Surname"], axis=1)

# Distinguish the feature and target set (5 points)

In [0]:
X = df.drop("Exited", axis=1)
y = df["Exited"]

In [14]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
X['Geography'] = labelencoder_x.fit_transform(X['Geography'])
X['Gender'] = labelencoder_x.fit_transform(X['Gender'])
X.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

# Divide the data set into Train and test sets

In [0]:
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y = train_test_split(X,y,test_size=0.3,random_state=42)

# Normalize the train and test data (5 points)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

# Initialize & build the model (10 points)

In [0]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
tf.keras.backend.clear_session()
model = Sequential()
model.add(Dense(activation = 'relu', input_dim = 10, units=6, kernel_initializer='uniform'))
model.add(Dense(activation = 'relu', units=6, kernel_initializer='uniform')) 
model.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform')) 
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [28]:
model.fit(train_x, train_y, batch_size=10, epochs=100)

W0901 06:07:07.703786 140144204539776 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

Epoch 1/100
7000/7000 [==============================] - 1s 202us/step - loss: 0.4978 - acc: 0.7924
Epoch 2/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4384 - acc: 0.7924
Epoch 3/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4326 - acc: 0.7924
Epoch 4/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4282 - acc: 0.8086
Epoch 5/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4255 - acc: 0.8197
Epoch 6/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4234 - acc: 0.8253
Epoch 7/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4218 - acc: 0.8277
Epoch 8/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4207 - acc: 0.8284
Epoch 9/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4197 - acc: 0.8283
Epoch 10/100
7000/7000 [==============================] - 1s 105us/step - loss: 0.4187 - acc: 0.8286
Epoch 11/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4180 - acc: 0.8294
Epoch 12/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4171 - acc: 0.8289
Epoch 13/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4165 - acc: 0.8294
Epoch 14/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4154 - acc: 0.8310
Epoch 15/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4144 - acc: 0.8297
Epoch 16/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4142 - acc: 0.8307
Epoch 17/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4136 - acc: 0.8314
Epoch 18/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4126 - acc: 0.8311
Epoch 19/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4122 - acc: 0.8319
Epoch 20/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4114 - acc: 0.8313
Epoch 21/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4111 - acc: 0.8319
Epoch 22/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4105 - acc: 0.8313
Epoch 23/100
7000/7000 [==============================] - 1s 104us/step - loss: 0.4106 - acc: 0.8310
Epoch 24/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4105 - acc: 0.8320
Epoch 25/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4101 - acc: 0.8301
Epoch 26/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4102 - acc: 0.8313
Epoch 27/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4094 - acc: 0.8307
Epoch 28/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4089 - acc: 0.8311
Epoch 29/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4090 - acc: 0.8311
Epoch 30/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4085 - acc: 0.8320
Epoch 31/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4089 - acc: 0.8316
Epoch 32/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4087 - acc: 0.8313
Epoch 33/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4085 - acc: 0.8316
Epoch 34/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4086 - acc: 0.8320
Epoch 35/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4082 - acc: 0.8314
Epoch 36/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4082 - acc: 0.8313
Epoch 37/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4075 - acc: 0.8316
Epoch 38/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4073 - acc: 0.8314
Epoch 39/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4077 - acc: 0.8336
Epoch 40/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4079 - acc: 0.8329
Epoch 41/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4077 - acc: 0.8331
Epoch 42/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4078 - acc: 0.8333
Epoch 43/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4075 - acc: 0.8324
Epoch 44/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4071 - acc: 0.8326
Epoch 45/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4077 - acc: 0.8323
Epoch 46/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4069 - acc: 0.8326
Epoch 47/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4067 - acc: 0.8323
Epoch 48/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4072 - acc: 0.8329
Epoch 49/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4071 - acc: 0.8319
Epoch 50/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4070 - acc: 0.8323
Epoch 51/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4066 - acc: 0.8330
Epoch 52/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4065 - acc: 0.8339
Epoch 53/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.4069 - acc: 0.8333
Epoch 54/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4063 - acc: 0.8343
Epoch 55/100
7000/7000 [==============================] - 1s 120us/step - loss: 0.4060 - acc: 0.8310
Epoch 56/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4063 - acc: 0.8317
Epoch 57/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4062 - acc: 0.8313
Epoch 58/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4052 - acc: 0.8316
Epoch 59/100
7000/7000 [==============================] - 1s 121us/step - loss: 0.4052 - acc: 0.8311
Epoch 60/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4050 - acc: 0.8313
Epoch 61/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4045 - acc: 0.8311
Epoch 62/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4043 - acc: 0.8326
Epoch 63/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4044 - acc: 0.8334
Epoch 64/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4047 - acc: 0.8316
Epoch 65/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4040 - acc: 0.8316
Epoch 66/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4036 - acc: 0.8334
Epoch 67/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4039 - acc: 0.8320
Epoch 68/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4039 - acc: 0.8321
Epoch 69/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4035 - acc: 0.8321
Epoch 70/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4032 - acc: 0.8310
Epoch 71/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4031 - acc: 0.8333
Epoch 72/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4031 - acc: 0.8319
Epoch 73/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4033 - acc: 0.8309
Epoch 74/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4035 - acc: 0.8323
Epoch 75/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.4032 - acc: 0.8331
Epoch 76/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4027 - acc: 0.8313
Epoch 77/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4031 - acc: 0.8317
Epoch 78/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4032 - acc: 0.8329
Epoch 79/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4027 - acc: 0.8313
Epoch 80/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4031 - acc: 0.8334
Epoch 81/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4030 - acc: 0.8321
Epoch 82/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4035 - acc: 0.8321
Epoch 83/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4029 - acc: 0.8317
Epoch 84/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4031 - acc: 0.8307
Epoch 85/100
7000/7000 [==============================] - 1s 118us/step - loss: 0.4026 - acc: 0.8319
Epoch 86/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4027 - acc: 0.8317
Epoch 87/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4031 - acc: 0.8329
Epoch 88/100
7000/7000 [==============================] - 1s 105us/step - loss: 0.4032 - acc: 0.8306
Epoch 89/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4032 - acc: 0.8321
Epoch 90/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4023 - acc: 0.8331
Epoch 91/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4031 - acc: 0.8329
Epoch 92/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4036 - acc: 0.8313
Epoch 93/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4032 - acc: 0.8314
Epoch 94/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4031 - acc: 0.8319
Epoch 95/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.4031 - acc: 0.8317
Epoch 96/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4028 - acc: 0.8319
Epoch 97/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4030 - acc: 0.8317
Epoch 98/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4025 - acc: 0.8340
Epoch 99/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4031 - acc: 0.8327
Epoch 100/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4029 - acc: 0.8310

# Optimize the model (Optional)

# Predict the results using 0.5 as a threshold (Optional)

# Print the Accuracy score and confusion matrix (5 points)

In [0]:
y_pred = model.predict(test_x)

In [33]:
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]

In [36]:
from sklearn.metrics import confusion_matrix, roc_auc_score
cm = confusion_matrix(test_y, y_pred)
print(cm)

[[2314  102]
 [ 370  214]]

In [37]:
roc = roc_auc_score(test_y,y_pred)
print(roc)

0.6621099065590129